# Generated by Django 4.0.3 on 2022-03-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slag',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=44, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
